export * from "./home"
export { default as Work } from "./work"
export {default as Blogs} from "./blogs"
export {default as Skills} from "./skills"
export {default as Contact} from "./contact"
export {default as About} from "./about"
export {default as Sitemap} from "./sitemap"
export * from "./blogs/BlogPage"